Question 2

In [6]:
import numpy as np

A = np.random.randint(-10, 11, size = (3, 3))

B = np.random.randint(-10, 11, size = (3, 3))

C = np.random.randint(-10, 11, size = (3, 3))

print('Matrix 1: ', A)
print('Matrix 2: ', B)
print('Matrix 3: ', C)  

Matrix 1:  [[-2 -2 -2]
 [ 3 -3 -5]
 [-8 -6 10]]
Matrix 2:  [[-1  8 -4]
 [ 2  5  7]
 [-3 -9  9]]
Matrix 3:  [[ 5  4  8]
 [ 7  8 -4]
 [ 1 -1  3]]


In [7]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)    

print('Inverse of Matrix 1: ', A_inv)
print('Inverse of Matrix 2: ', B_inv)
print('Inverse of Matrix 3: ', C_inv)

Inverse of Matrix 1:  [[-0.32608696  0.17391304  0.02173913]
 [ 0.05434783 -0.19565217 -0.08695652]
 [-0.22826087  0.02173913  0.06521739]]
Inverse of Matrix 2:  [[-0.26470588  0.08823529 -0.18627451]
 [ 0.09558824  0.05147059  0.00245098]
 [ 0.00735294  0.08088235  0.05147059]]
Inverse of Matrix 3:  [[-0.16666667  0.16666667  0.66666667]
 [ 0.20833333 -0.05833333 -0.63333333]
 [ 0.125      -0.075      -0.1       ]]


In [10]:
print('Verification of Matrix 1: ', A @ A_inv)
print('Verification of Matrix 2: ', B @ B_inv)
print('Verfication of Matrix 3: ', C @ C_inv)

Verification of Matrix 1:  [[ 1.00000000e+00 -2.08166817e-17  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00  1.38777878e-17]
 [ 5.55111512e-17 -1.17961196e-16  1.00000000e+00]]
Verification of Matrix 2:  [[ 1.00000000e+00 -5.55111512e-17  2.77555756e-17]
 [ 1.73472348e-17  1.00000000e+00  3.46944695e-17]
 [-1.73472348e-17 -4.16333634e-17  1.00000000e+00]]
Verfication of Matrix 3:  [[ 1.00000000e+00  0.00000000e+00  3.33066907e-16]
 [ 1.11022302e-16  1.00000000e+00  2.77555756e-16]
 [ 8.32667268e-17 -2.77555756e-17  1.00000000e+00]]
